services:
  - type: web
    name: carwatch
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn src.web.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: DATABASE_URL
        fromDatabase:
          name: carwatch-db
          property: connectionString

databases:
  - name: carwatch-db
    databaseName: carwatch
    user: carwatch
    